services:
  - type: web
    name: deus-proverar
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: ADMIN_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: deus_proverar
